server:
  port: 9000
logging:
  config:
    classpath: log4j2.xml

bee:
  provider:
    name: kafka1x  #servlet,kafka1x
    kafka1x:
      idleSleep: 5000 #队列为空时候，线程休眠时间，默认100ms
      pollTimeout: 2000 #kafka拉取超时时间，默认1000ms
      topics: bee-default,bee-process,bee-process-param,bee-sql,bee-sql-param,bee-request,bee-request-param,bee-logger
      kafkaConfig:
        #kafka配置值项，项名称和值请参考kafka文档
        bootstrap.servers: 118.31.50.102:6000
        max.poll.records: 5 #默认500
  store:
    name: elasticsearch
    elasticsearch:
       config:
         url: http://es.skyeye.cc:8000
  #      username: xx
  #      password: xx
  #      connTimeout: 6000
  #      readTimeout: 6000
  #      defaultMaxTotalConnectionPerRoute: 2
       indices:
          default: bee-default #配置默认topic，没有配置映射关系的，数据写到该topic
          proc: bee-process
          para: bee-process-param
          sql: bee-sql
          sqlp: bee-sql-param
          req: bee-request
          rp: bee-request-param
          tx: bee-tx
          log: bee-logger
          err: bee-error
          reqb: bee-request-body
          reqh: bee-request-headers
          respb: bee-response-body
          hb: bee-heartbeat
  handlers:
    flow: empty>json>queue>store
    queue:
      queueSize: 5000 #队列大小，默认5000
      threadNum: 2 #默认cpu核数
      sleep: 100
      batchSize: 100
      maxLoopTimes: 3