server:
  port: 8001
logging:
    config:
      classpath: log4j2.xml
# 配置项参考类io.searchbox.client.config.HttpClientConfig.Builder里的方法，配置项与方法名称对应.
elasticsearch:
    url: http://192.168.137.100:9200,http://192.168.137.100:9201
    #username: es
    #password: 123
    connTimeout: 30000
    readTimeout: 30000
    multiThreaded: true
