server:
  port: 9000
logging:
    config:
      classpath: log4j2.xml
# 配置项参考类io.searchbox.client.config.HttpClientConfig.Builder里的方法，配置项与方法名称对应.
elasticsearch:
    url: http://es.skyeye.cc:8000
    username: es
    password: 123
    connTimeoutMs: 30000
    readTimeoutMs: 30000
