logger:
    console: true  #日志输出到控制台，默认false
    level: trace   #日志输出级别，默认error
    fileSize: 10485760 #日志文件大小，单位字节,默认10M
    fileNum: 3     #日志文件保留数量，默认5个文件
heartbeat:
    period: 300 #心跳周期，单位秒,默认60
reporter:
    queueSize: 200 #缓冲队列大小，默认1000
    threadNum: 2   #从队列读取数据并发送的线程数，默认cpu核数availableProcessors
    idleSleep: 100 #队列为空时候，线程休眠时间，默认100ms
    batchSize: 20  #每次从队列中批量获取数据数量，默认100
    name: kafka1x  #使用哪种reporter支持console,okhttp,kafka1x,rocketmq
    log: true      #是否以logger.debug输出上报的日志数据
    okhttp:        #name对应的reporter的配置参数
        connectTimeout: 30
        writeTimeout: 10
        readTimeout: 10
        url:
            - http://127.0.0.1:7001/stream
            - http://127.0.0.1:7001/stream
    kafka1x:
        kafkaConfig:
            #kafka配置值项，项名称和值请参考kafka文档
            bootstrap.servers: 192.168.137.100:9092
            linger.ms: 200
        topic: #配置span type和kafka topic映射关系
            default: bee-default #配置默认topic，没有配置映射关系的，数据写到该topic
            proc: bee-process
            para: bee-process-param
            sql: bee-sql
            sqlp: bee-sql-param
            req: bee-request
            rp: bee-request-param
            tx: bee-tx
            log: bee-logger
            err: bee-error
            reqb: bee-request-body
            reqh: bee-request-headers
            resb: bee-response-body
            hb: bee-heartbeat
            topo: bee-topology
    rocketmq:
        #kafka配置值项，项名称和值请参考kafka文档
        nameSrvAddr: 192.168.2.244:9876
        instanceName: rmq-instance
        producerGroup: rmq-group
        topic: #配置span type和kafka topic映射关系
            default: bee-default #配置默认topic，没有配置映射关系的，数据写到该topic
            proc: bee-process
            para: bee-process-param
            sql: bee-sql
            sqlp: bee-sql-param
            req: bee-request
            rp: bee-request-param
            tx: bee-tx
            log: bee-logger
            err: bee-error
            reqb: bee-request-body
            reqh: bee-request-headers
            respb: bee-response-body
            hb: bee-heartbeat
            topo: bee-topology
sampling:
    rate: 10000 #采样率，万分几，默认全采集,比如100就是100/10000的采样
id:
    zk:
        url: 192.168.137.100:2181
        timeout: 5000
        retryTimes: 3
        retrySleep: 5000
    start: 5000
plugins:
    process:
        enable: true  #采集开关
        spend: -1 #耗时阀值
        enableMethodSign: true #是否采集方法签名,默认false
        param:
            enable: true  #参数采集开关
            excludeTypePrefix: #排除的参数类型，参数不被系列化
                - org.apache.velocity.
                - javax.
                - org.w3c
                - org.springframework
                - org.apache
                - org.jdom
                - com.fasterxml
                - org.mybatis
                - com.fasterxml
                - net.sf.json
                - org.codehaus
                - java.lang.reflect
                - java.lang.Object
                - java.io
                - java.nio
                - sun.nio
                - org.aspectj
            excludePointMatches: #正则表达式，排除的采集点的参数不被采集，可以配置到方法级别，优先级别高于includePointPrefix
                - com.asiainfo.rule.*
            includePointMatches:  #正则表达式，包含的采集点的参数才被采集，可以配置到方法级别，不配置的话默认都采集，前提在interceptPoints的前提下
                - com.asiainfo.*
        error:
            enable: true
            #白名单配置，不在白名单的不采集，该前缀是在interceptPoint的前提下，支持到方法级别(fullClassName.methodName)
            includeErrorPointPrefix:
                - net.beeapm.demo
            #黑名单配置，优先级别最高，该前缀是在interceptPoint的前提下，支持到方法级别(fullClassName.methodName)
            excludeErrorPointPrefix:
        #采集范围配置，请根据自己的情况，调整下采集范围
        interceptPoints:
            -
                typeMatch:  #类匹配规则
                    include: #包含规则named,nameStartsWith,nameEndsWith,nameContains,nameMatches,hasSuperType,hasAnnotation
                        nameStartsWith: net.beeapm.demo
                    exclude: #排除规则named,nameStartsWith,nameEndsWith,nameContains,nameMatches,hasSuperType,hasAnnotation
                        nameContains: CGLIB
                        nameStartsWith:
                methodMatch: #方法匹配规则
                    include: #包含规则named,nameStartsWith,nameEndsWith,nameContains,nameMatches,isAnnotatedWith
                        named:
                    exclude: #排除规则named,nameStartsWith,nameEndsWith,nameContains,nameMatches,isAnnotatedWith
                        named:

    jdbc:
        enable: true       #开关，是否采集
        spend: -1           #耗时阀值
        enableParam: true  #参数采集开关
    logger:
        enable: true    #开关，是否采集,默认true
        errorRate: false #开关，error及以上级别是否使用采样率,默认false
        defLevel: debug #默认级别，默认值为debug
        points:
        #日志采集点配置，规则为包名和日志级别，如a.b.c|debug，日志级别可不配置，为默认defLevel级别
            - com.asiaifo|error
            - com.asiainfo.crm|debug
            - net.beeapm.demo|info
    servlet:
        enable: true       #开关，是否采集
        enableReqParam: true #参数采集开关，是否采集
        enableReqBody: true  #RequestBody采集开关，是否采集
        enableReqHeaders: true  #Request headers采集开关，是否采集
        enableRespBody: true # response采集开关，是否采集
        spend: 1           #耗时阀值，小于等于process.spend
        urlSuffixExclude: .html,.jsp,hello2 #url后缀排除，多个用逗号分开
    springTx:
        enable: true       #开关，是否采集
        spend: 0           #耗时阀值



